language: ruby
rvm:
  - "2.0.0"
bundler_args: --without development
before_script:
  - psql -c 'create database ping_test;' -U postgres
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - rake db:migrate
script: bundle exec rspec