language: ruby
rvm:
  - "2.1.0"
before_install: gem install bundler -v=1.5.1
bundler_args: --without development
before_script:
  - psql -c 'create database ping_test;' -U postgres
  - export RUBY_GC_MALLOC_LIMIT=50000000
  - rake db:migrate
script: bundle exec rspec